### ISSUE TITLE
Сгради

### ISSUE THREAD

**Issue by kKunov** [JTCom/Leap#11]
ЧЕТИ ДО КРАЙ ПРЕДИ ДА ПОЧНЕШ!!!

Направи нов файл `buildingsAndLocations.pug` във папката `views/masterDataPages`. В него ще си създадеш таблица (прелагам да ѝ съсздадеш всичко, без съдържанието на Body-то ѝ).

В таблицата ще трябва да има всички колонки които има в базата в таблицата `locations`, без `location_id`. Вместо `building_id`  ще се взимаш `building_name` от таблицата `buildings`.

Над таблицата трябва да има:

-  бутон за добавяне на ред (който да отваря модал в който да се попълнят съответните колонки).

- search `input` който при натискане на клавиш да търси във всички колонки от таблицата и да скрива тези редове, които не съдържат в нито една колонка, стойността която е изписана.

Създай си buildingsAndLocations.js файлове във следните папки: `public/js` и `routes`.

За да почнеш пъг файла виж някой от пъговете във `views/weeklySchedulePages`, a стойността на атрибута `data-sec-view-name` от `views/mainPages/index.pug`.

При въпроси питай.

Инджой!

**Comment by lukeskychrono** [comment]
Пушнал съм, прегледай го.. Когато можеш се свържи с мен, има някои неща за уточняване.

**Comment by kKunov** [comment]
- В бек енда има коментари, на 2 места, сложете валидации дали нужните колонки са цифри.

- Преведете всичко във ваща страница на Булгериън.

**Comment by lukeskychrono** [comment]
Готово.

**Comment by kKunov** [comment]
Е казах ти че има 2 коментара във тоя файл, пък ти си оправил нещата при първия, виж и другия, щото и там трябва да се валидират нещата
