### ISSUE TITLE
Потребители

### ISSUE THREAD

**Issue by kKunov** [JTCom/Leap#16]
ЧЕТИ ДО КРАЙ ПРЕДИ ДА ПОЧНЕШ!!!

Направи нов файл `users.pug` във папката` views/masterDataPages`. В него ще си създадеш таблица (прелагам да ѝ съсздадеш всичко, без съдържанието на Body-то ѝ).

В таблицата ще трябва да има всички колонки които има в базата в таблицата `users,` без `user_id`. 

Над таблицата трябва да има:

- бутон за добавяне на ред (който да отваря модал в който да се попълнят съответните колонки).

- search `input `който при натискане на клавиш да търси във всички колонки от таблицата и да скрива тези редове, които не съдържат в нито една колонка, стойността която е изписана.

Създай си users.js файлове във следнaтa папкa: public/js.

За да почнеш пъг файла виж някой от пъговете във `views/administrationPages`, a стойността на атрибута `data-sec-view-name` от `views/mainPages/index.pug`.

При въпроси питай.

Инджой!

**Comment by kKunov** [comment]
Преведи си сичко в твойта страница на Булгериън.

**Comment by kKunov** [comment]
Виж си моляте и бутоните в края на модала, нещо не се държат хубаво, провери ги пак моля те.

**Comment by kKunov** [comment]
В модала, вместо h4 ползвай label. Осве това не слагай input-ите в дивове, нека са siblings на label-ите

**Comment by Ivanostotel** [comment]
Използвах h4 защото с label сбиваше целият текст до полето и изглеждаше трагично
