### ISSUE TITLE
Продължение на 'Сгради #11'

### ISSUE THREAD

**Issue by kKunov** [JTCom/Leap#17]
1. В модала за Сградите трябва да добавите едно тикче, което да показва че сградата е 'Ректорат', за да се определи дали трябва да се показва това тикче правете следната заявка: `SELECT building_id FROM buildings WHERE primary_flag = 1;` Ако дължината на отговора е повече от 0, не показвайте това тикче!!!

2. Във модала за създаване на нова стая, направете полетата които ходят в базата като цифрови, да са с type="number".  Полето 'Projector Flag', го направете select с възможности 'да' и 'не'.

**Comment by kKunov** [comment]
По първата точка: Когато създадеш Ректорат и НЕ рефрешнеш страницата и след това създадеш нова сграда, тя също отива с 1 в primary_flag колонката. Това става защото не махаш тикчето от checkbox-а, преди да затвориш модала при първото създаване на сграда

**Comment by kKunov** [comment]
Освен това искам в другия модал да е винаги избрано 'ДА' за проектор. След като си създал нова стая и пробваш втори път, за това поле не е избрано нищо.

**Comment by lukeskychrono** [comment]
Моля за merge между mstoyanov2258 и PRadev бранчове, тъй като е възможно да възникнат конфликти.

**Comment by kKunov** [comment]
Готово, направете `pull` и двамата

**Comment by kKunov** [comment]
Направете го да може да се едитва ред от таблицата. Добавете бутон над таблицата за тази цел. Когато се кликне на ред да му се добавя клас актив и да се махне от другите редове ако някой го има.

При клик на новосъздадения бутон, да се появява модал за едит (със същите полета като creatе), но да се попълва с данните от реда.

**Comment by lukeskychrono** [comment]
Виж го, отдавна е завършено и го затваряй направо :)
