### ISSUE TITLE
Дисциплини 2

### ISSUE THREAD

**Issue by kKunov** [JTCom/Leap#25]
В страницата дисциплини, добави функционалност да се edit-ва информацията за дисциплина.

Как да стане това:

1. Направи редовете да се избират (когато кликнеш на ред той да се маркира, ако има вече избран ред той да се демаркира). Това става като добавиш на кликнатия ред клас `active`

2. Добави бутон 'Промени дисциплина', над таблицата. Да бъде неактивен. Да става активен когато се избере ред от таблицата.

3. При кликване на бутона от 2-ра точка, да се отваря модал който да има същите полета като модала който се отваря когато се създава преподавател, но те да са попълнени със стойностите от съответния ред.

4. Заявката в back-end-а ще е UPDATE,  не INSERT INTO, ето ти линк да си я видиш как се прави:
[UPDATE](https://www.w3schools.com/sql/sql_update.asp)

Файловете в които трябва да работиш са:
- public/js/subject.js
- routes/subject.js
- views/masterDataPages/subject.pug
- views/masterDataPages/modals.pug

**Comment by KristyMyers** [comment]
Готова съм. Пуснах го.
