### ISSUE TITLE
Нова страница, Teachers Calendar

### ISSUE THREAD

**Issue by kKunov** [JTCom/Leap#5]
Създай нова страница, Teachers Calendar
    Страницата се създава като създадеш нов pug файл в папка /views/pages
    После трябва да го добавиш във файл /views/index.pug
Създай си нов js файл във /publick/js/
Добави го в /views/layout.pug (по аналогия на другите)
В /views/pages/modals.pug създай нов modal, в който да има само 2 радио бутона: 
1. Зает в интервала
2. Предпочитан интервал

Направи модала да се отваря от бутон във Teachers Calendar страницата.

За модалите можеш да четеш тук:
https://getbootstrap.com/docs/3.3/javascript/#modals
Виж им и евентите.

**Comment by kKunov** [comment]
Не искам радио бутоните да са като бутони, искам да са си нормални радио бутони!!! Оправи си ги моля те.

**Comment by KristyMyers** [comment]
Готова съм. Оправих го.

**Comment by kKunov** [comment]
Супер
