### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by kKunov** [JTCom/Leap#6]
При resize на event - да се отразява в останалите календари.

**Comment by kKunov** [comment]
Има един бъг, който се появи когато мърджнах твоя клон с този на Павката:

Когато смениш главния календар, евентите за предпочитанията на преподавателите изчезват, ще трябва да извикваш ф-ята с която той ги зарежда, за да се показват и те.

Оправи го ти.

**Comment by lukeskychrono** [comment]
Готово.
